### ISSUE TITLE
Unable to create an Employee at Deputy (array_merge(): Argument #1 must be of type array, null given)

### ISSUE THREAD

**Issue by WaheedNodesol** [communityds/deputy-api-wrapper#22]
My Composer.json File
{
    "require": {
        "communityds/deputy-api-wrapper": "^1.6",
        "guzzlehttp/guzzle": "^6.0"
    }
}

My PHP Verion: 8.2, I also have tried with 7.4, both showing the same issues.

My PHP Example Code

    $wrapper = DeputyWrapper::getInstance();

    $employee = $wrapper->createEmployee();
    $employee->firstName = 'Jane';
    $employee->lastName = 'Doe';
    $employee->setFields(
        [
            'displayName' => 'Jane Doe',
            'active' => true,
            'allowAppraisal' => false
        ]
    );
    $employee->save();

Error Detail:
'#0 /home/nodesol/public/vendor/communityds/deputy-api-wrapper/src/Schema/ResourceInfo.php(161): array_merge() #1 /home/nodesol/public/vendor/communityds/deputy-api-wrapper/src/Schema/Registry.php(73): CommunityDS\\Deputy\\Api\\Schema\\ResourceInfo->loadDefinitions() #2 /home/nodesol/public/vendor/communityds/deputy-api-wrapper/src/Wrapper.php(457): CommunityDS\\Deputy\\Api\\Schema\\Registry->resource() #3 /home/nodesol/public/index.php(8): CommunityDS\\Deputy\\Api\\Wrapper->__call() #4 {main}''array_merge(): Argument #1 must be of type array, null given'

**Comment by SonOfHarris** [comment]
Thanks @WaheedNodesol for letting us know of the issue. I'll take a deep dive to try to find the cause.

The stack trace indicates it may be an issue with the schema returned by Deputy, or that it's an issue in how the wrapper handles the schema.

**Comment by SonOfHarris** [comment]
@WaheedNodesol Could I ask you to provide some debugging information.

Please install the Deputy API Console and configure it for the environment you are experiencing the issue on: https://github.com/communityds/deputy-api-console

Then run the following command:

```
./console schema Employee -vvv
```

Please paste the response here as I have a feeling it might be something in your Deputy environment. In other resources the `assocs` key is always present even if empty so I'm not sure why it would be null or non-existent.

**Examples:**

Below is an example that I receive from my sandbox Deputy environment that includes `fields`, `joins` and `assocs`:

```
[debug] GET resource/Employee/INFO
[debug] Response Code: 200

{"fields":{"Id":"Integer","Company":"Integer","FirstName":"VarChar","LastName":"VarChar","DisplayName":"VarChar","OtherName":"VarChar","Salutation":"VarChar","MainAddress":"Integer","PostalAddress":"Integer","Contact":"Integer","EmergencyAddress":"Integer","DateOfBirth":"Date","Gender":"Integer","Pronouns":"Integer","CustomPronouns":"VarChar","Photo":"Integer","UserId":"Integer","JobAppId":"Integer","Active":"Bit","StartDate":"Date","TerminationDate":"Date","StressProfile":"Integer","Position":"VarChar","HigherDuty":"Bit","Role":"Integer","AllowAppraisal":"Bit","HistoryId":"Integer","CustomFieldData":"Integer","OnboardingId":"VarChar","Creator":"Integer","Created":"DateTime","Modified":"DateTime"},"joins":{"CompanyObject":"Company","MainAddressObject":"Address","PostalAddressObject":"Address","ContactObject":"Contact","EmergencyAddressObject":"Address","StressProfileObject":"StressProfile","RoleObject":"EmployeeRole","CustomFieldDataObject":"CustomFieldData"},"assocs":{"PayRules":"PayRules","ManagementEmployeeOperationalUnit":"OperationalUnit","RosterEmployeeOperationalUnit":"OperationalUnit","Employee":"Team"},"count":6}
```

Here's another example where `assocs` is an empty array:

```
[debug] GET resource/Address/INFO
[debug] Response Code: 200

{"fields":{"Id":"Integer","ContactName":"VarChar","UnitNo":"VarChar","StreetNo":"VarChar","SuiteNo":"VarChar","PoBox":"VarChar","Street1":"VarChar","Street2":"VarChar","City":"VarChar","State":"VarChar","Postcode":"VarChar","Country":"Integer","Phone":"VarChar","Notes":"Blob","Format":"Integer","Saved":"Bit","Creator":"Integer","Created":"DateTime","Modified":"DateTime"},"joins":[],"assocs":[],"count":573}
```

**Comment by SonOfHarris** [comment]
Alternatively add a `logger` configuration to the wrapper as that's what the console uses to get the raw responses:

https://github.com/communityds/deputy-api-wrapper/blob/master/docs/logging.md
